#  2013-10-10 (cc) <paul4hough@gmail.com>

dist: trusty
language: c
notifications:
  email:
    - paul4hough@gmail.com

before_script:
  - sudo apt -y install emacs git automake
  - emacs --version
  - autoconf --version

script:
  - autoreconf
  - ./configure
  - make test-system
  - make install
